module AdaBoost

  module Config
    NUMBER_OF_RANDOM_CLASSIFIERS = 100
    INCORPORATE_COST_SENSITIVE_LEARNING = true
    OVER_SAMPLING_TRAINING_SET = false
    USE_RANDOM_WEAK_CLASSIFIERS = false
    USE_THRESHOLD_CLASSIFICATION = true
  end
end
